#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/sw/lsa/centos7/neuron/7.8.0"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/sw/lsa/centos7/neuron/7.8.0/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/mirzakh/TI/cells/x86_64/.libs/libnrnmech.so" "$@"
